# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to='picture/'),
        ),
    ]
